#************************ GAAP-BI v. 1.0 config file *************************#

#********** MIT LICENSE - Copyright © 2022 Benucci Jones Broderick ***********#
#********************* email: benucci[at]msu[dot]edu *************************#

#********************** metaGAAP v1.0 config file ****************************#
echo -e "Reading metaGAAP-v.1.0.sh config.yaml"

# Change based on user HPCC account. Deafult project directory is metaGAAP
project_dir="/mnt/home/jones514/metaGAAP" 

# Default to rawdata directory
cd $project_dir/rawdata/

# Change your username based on MSU ID 
MSUusername="jones514"

# Databases
NCBI_nt="/mnt/research/EvansLab/DATABASES/ncbi_newest"
kraken2_db="/mnt/research/EvansLab/DATABASES/kraken2_db"
phix_db="/mnt/research/EvansLab/DATABASES/phix_db/my_phix"

# Running Parameters. If not numeric (i.e. float) then 'yes' or 'no'.
LENGTH=1000
COVERAGE=0.01

# PATHs
export EGGNOG_DATA_DIR=/mnt/research/ShadeLab/Benucci/databases/emapperdb/
#****************************************************************************#
